version: "3.8"
services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "./tmp/data:/var/lib/mysql"
      - "./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    env_file:
      - ".env"
