FROM node:18.12.1-alpine

ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PATH:$PNPM_HOME
ENV PNPM_VERSION=8.3.1

RUN apk update \
  && apk upgrade \
  && apk add --no-cache curl \
  && curl -fsSL "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" -o /bin/pnpm \
  && chmod +x /bin/pnpm

WORKDIR /usr/app

CMD ["pnpm", "start:dev"]
