name: Deploy

on:
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: mysql://${{ secrets.PRISMA_USER }}:${{ secrets.PRISMA_PASSWORD }}@${{ secrets.DB_ADDR }}/${{ secrets.PRISMA_DATABASE }}
  WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
  WAYPOINT_SERVER_ADDR: ${{ secrets.WAYPOINT_SERVER_ADDR }}
  WAYPOINT_SERVER_TLS: 1
  WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8.3.1
        run_install: false

    - name: Setup Node.js v18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'

    - name: Install client dependencies
      # working-directory: app/client
      run: ls -la && cd app/client && pnpm i

    - name: Build client
      working-directory: app/client
      run: pnpm build

    - name: Install server dependencies
      working-directory: app/server
      run: pnpm i

    - name: Build server
      working-directory: app/server
      run: pnpm build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Install waypoint
      uses: hashicorp/action-setup-waypoint@main
      with:
        version: '0.1.0'

    - run: waypoint init

    - name: Start db
      run: |
        waypoint up \
        -var prisma_database=${{ secrets.PRISMA_DATABASE}} \
        -var prisma_user=${{ secrets.PRISMA_USER }} \
        -var prisma_password=${{ secrets.PRISMA_PASSWORD}} \
        -var mysql_root_password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
        -var docker_username=${{ secrets.DOCKER_USERNAME }} \
        -var jwt_secret=${{ secrets.JWT_SECRET }} \
        -var hash_salt=${{ secrets.HASH_SALT }} \
        -var node_env=production \
        -app=db

    - name: Start app
      run: |
        waypoint up \
        -var prisma_database=${{ secrets.PRISMA_DATABASE}} \
        -var prisma_user=${{ secrets.PRISMA_USER }} \
        -var prisma_password=${{ secrets.PRISMA_PASSWORD}} \
        -var mysql_root_password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
        -var docker_username=sashkashishka \
        -var jwt_secret=${{ secrets.JWT_SECRET }} \
        -var hash_salt=${{ secrets.HASH_SALT }} \
        -var node_env=production \
        -app=app
